### ISSUE TITLE
HMR seems to mess the store/state

### ISSUE THREAD

**Issue by flayks** [sveltejs/svelte-hmr#6] opened 2020-02-07 10:08 UTC
I keep having this issue on screen with `svelte-hmr` (using Sapper tho)

```
Failed to init component
<[location]>
TypeError: page.set is not a function
    at Location.$$self.$inject_state (http://127.0.0.1:38670/client/@hot/src/routes/location/[country]/[location].js:706:35)
    at restoreState (http://127.0.0.1:38670/client/@hot/node_modules/.pnpm/registry.npmjs.org/svelte-hmr/0.1.4/node_modules/svelte-hmr/runtime/svelte-hooks.js:87:15)
    at createComponent (http://127.0.0.1:38670/client/@hot/node_modules/.pnpm/registry.npmjs.org/svelte-hmr/0.1.4/node_modules/svelte-hmr/runtime/svelte-hooks.js:158:13)
    at Location.targetCmp.$replace (http://127.0.0.1:38670/client/@hot/node_modules/.pnpm/registry.npmjs.org/svelte-hmr/0.1.4/node_modules/svelte-hmr/runtime/svelte-hooks.js:200:21)
    at refreshComponent (http://127.0.0.1:38670/client/@hot/node_modules/.pnpm/registry.npmjs.org/svelte-hmr/0.1.4/node_modules/svelte-hmr/runtime/proxy.js:126:29)
    at ProxyAdapterDom.rerender (http://127.0.0.1:38670/client/@hot/node_modules/.pnpm/registry.npmjs.org/svelte-hmr/0.1.4/node_modules/svelte-hmr/runtime/proxy-adapter-dom.js:72:11)
    at refreshComponent (http://127.0.0.1:38670/client/@hot/node_modules/.pnpm/registry.npmjs.org/svelte-hmr/0.1.4/node_modules/svelte-hmr/runtime/proxy.js:116:23)
    at ProxyAdapterDom.rerender (http://127.0.0.1:38670/client/@hot/node_modules/.pnpm/registry.npmjs.org/svelte-hmr/0.1.4/node_modules/svelte-hmr/runtime/proxy-adapter-dom.js:72:11)
    at http://127.0.0.1:38670/client/@hot/node_modules/.pnpm/registry.npmjs.org/svelte-hmr/0.1.4/node_modules/svelte-hmr/runtime/proxy.js:303:15
    at Array.forEach (<anonymous>)
```

I basically fetch a request to get photos from the current URL and update a store writable like this:
```js
// ...
import { apiEndpoints, site, locations, currentLocation } from '../../../store'
import { stores } from '@sapper/app'
// ...
const { page } = stores()
// ...
// Update current location
const location = $locations.find(loc => loc.slug === $page.params.location)
currentLocation.set({ location, photos })

// Define full location
const locationFull = `${location.name}, ${location.country.name}`
```

But whenever I update something in a variable or anything, I get the previous error. Tried many things but can't see why. This is not replicating using a more standard rollup config without HMR/svelte-hot.

**Comment by flayks** [comment] 2020-02-07 10:14
It also looks that exporting props could be a problem as [this issue](https://github.com/rixo/svelte-hmr/issues/5) mentions it?
I initially preload photos from my API for this specific page, then export it in my page `<script>`

```svelte
<script context="module">
	import { apiEndpoints } from '../../../store'

	// Preload
	export async function preload (page, session) {
		// Load photos
		const req = await this.fetch(`${apiEndpoints.rest}/items/photos?fields=id,name,date,slug,image.data,created_on,modified_on&filter[location.slug][rlike]=%${page.params.location}%&sort=-created_on,name`)
		const photos = await req.json()
		if (req.status === 200) {
			return { photos: photos.data }
		}
		this.error(404, 'Not found')
	}
</script>
```
```svelte
<script>
// ...
export let photos
// ...
currentLocation.set({ location, photos })
// ...
</script>
```

Without doing a `export let photos` in my route `<script>`, it works fine.

**Comment by rixo** [comment] 2020-02-07 20:31
Yes, there's a problem with store autosubcriptions in the current version. Should be fixed by [this PR](https://github.com/sveltejs/svelte/pull/3822/files#diff-ed90ad8369bd511ed5bca57f60349123R175) (the `v.name[0] !== '$'` in this line means "don't try to inject store subscriptions").

Can you try the [next version](https://github.com/rixo/svelte-template-hot/blob/144628cc5b05184a74671874872a79faf8c0f525/package.json#L14) to see if it solves your issue?

~~~bash
yarn add -D rollup-plugin-svelte-hot@next rixo/svelte#hmr-capture-state-dist
~~~

Note: this is using a forked version of Svelte maintained by myself.

As I explained in the other issue, this PR should fix a lot of things for preservation of local state and reactive blocks. So any feedback regarding the implementation in the `next` version is very welcome currently.

**Comment by rixo** [comment] 2020-02-28 23:00
@flayks Hey! The problem should be fixed with the last version of the plugin (for Rollup, from what I see -- hey, you're using this with pnpm? cool!), and Svelte 3.19+. Can you confirm the problem is fixed on your side?

**Comment by flayks** [comment] 2020-02-29 10:38
Thanks for the heads up @rixo! It seems like that fixes the issue, so far no problems with any state errors.

Also, it's not super related but I can't get the HMR working with `sveltePreprocess` and SCSS. All I get when updating `.scss` files is a `[HMR] Rebuilding...` in the console and no visual updates, either with a `bundle.css` file or using the built in styles from the template (`%sapper.styles%`).
Do you have any idea? Because then I still have to manually refresh the page to see the changes.

**Comment by rixo** [comment] 2020-03-01 15:19
You're very welcome, your feedback is really useful :)

So yeah, this is totally unrelated... But I'm interested in fixing any use case for people who care enough for trying & reporting.

Regarding SCSS, I've got a vague idea, yeah... The underlying `rollup-plugin-hot` has no support whatsoever for reloading CSS. I've already experimented a few times with `rollup-plugin-postcss` and it appears to be quite possible ([my last experiment](https://github.com/rixo/svelte-template-hot/blob/example-smui/rollup.config.js#L92) if you're curious).

That would probably have to be done on the CSS plugin side, but I'm happy to investigate and bring the discussion to the relevant projects, if you open an issue with some details about your config (what plugin(s) you are using, and the relevant parts of plugin / rollup config -- or whole and I'll sort it out).

I'm closing this one since the issue with stores is resolved.

**Closed as completed** 2020-03-01 15:19 UTC
