### ISSUE TITLE
HMR is restoring internal state if a component has at least one exported property

### ISSUE THREAD

**Issue by jsprog** [sveltejs/svelte-hmr#5] opened 2020-02-06 21:37 UTC
This issue is affecting Rollup, Nollup and Webpack

1. Create a new project using either rollup or webpack template
2. Open App.svelte and replace content with code listed below:
3. Run the development server
4. Edit App.svelte (e.g: by adding emply lines), then save to force HMR
5. Inspect the logs

**Code:**
```
<!-- HMR is breaking the binding -->
<div bind:this={targetElement}>target element</div>

<script>
    export let name // comment this line to kill all problems
    import { onMount, onDestroy, tick } from 'svelte'

	let interval
	let targetElement

	onMount(async () => {
		interval = setInterval(() => { console.log('interval...') }, 1000)

		console.log('before tick:')
		console.log('targetElement:', targetElement) // referencing the new dom element after HMR
		console.log('parent:', targetElement.parentNode) // 'body' is the parent
		console.log('interval:', interval)
		console.log('')

		await tick() // issue: restoring non exported state is done during this phase.

		console.log('after tick:')
		console.log('targetElement:', targetElement) // issue: referencing the older element, and no longer referencing the current dom element. use chrome dev tools and hover on the log to confirm
		console.log('parent:', targetElement.parentNode) // 'null'
		console.log('interval:', interval) // even interval is replaced with the old value, and the correct value for use during destruction is lost
		console.log('')
	})

	onDestroy(() => {
		// issue: targetElement is still referencing the oldest element
		
		console.log('onDestroy:')
		console.log('interval:', interval) // issue: interval is referencing the first ever created interval and no way to stop it
		console.log('')
		clearInterval(interval) // this isn't destroying the recently created interval
	})
</script>
```

**Comment by rixo** [comment] 2020-02-07 20:17
Hey! Thanks for reporting.

If I get it correctly, the problem is that the parent element is lost after HMR update?

This seems to be fixed in the [`next`](https://github.com/rixo/svelte-hmr/tree/next) version (should be released when [this PR](https://github.com/sveltejs/svelte/pull/3822) is merged).

Can you try and confirm on your side?

~~~bash
npx degit rixo/svelte-template-hot#next app
cd app
yarn
yarn dev
~~~

Behaviour for local state (i.e. non exported) and reactive blocks is not really stable currently. This PR should settle a lot of things.

However, with fully working preservation of local state, I came to realize that it could be pretty troublesome to not have values reset at times... Really depends on the situation. For now I've implemented a quick hack: if you put a `'@!hmr'` string somewhere in your component, then local state will not be preserved for the ensuing HMR update. Otherwise, you still have the [`noPreserveState`](https://github.com/rixo/svelte-template-hot/blob/master/rollup.config.js#L55) option, if you want to turn it off completely.

Actually, I'm not entirely certain of what the best behaviour should be for this... So if you play with the `next` branch and you find some behaviour that conflicts with your own expectation, I'm very interested to hear!

**Comment by jsprog** [comment] 2020-02-08 07:50
Hello again.

I already followed your instructions and now:

- Restoration of local state is done before calling the onMount callback, and no longer messing with the references created during it.
- I already confirmed that HMR isn't messing with bindings to DOM elements anymore.

I really understand that local state preservation may be useful in many situations and I'm really convinced about keeping it as the the default mode. But adding something like '@!hmr' anywhere in the file is quite a mess and better to only allow it at the top.

**Comment by rixo** [comment] 2020-02-08 14:45
I'm reading this as "problem solved in next version", correct?

---

> adding something like '@!hmr' anywhere in the file is quite a mess and better to only allow it at the top.

One common use case is that you'll want to reset state just for one update. So you'd add `@!hmr` just where you are editing in the file, save, and remove it. For example, if you've changed the initial value of a variable (which value would otherwise be preserved across update). That's why I think it's better to accept it anywhere.

It also avoids the problem of "where does the top of the file end?". I mean, if there's another plugin that wants its comment "at the top of the file", how can I know that the 2nd line is still the top? It's a Pandora box, better not to touch it.

People can still keep it at the top as a project convention, for annotations that are intended to be kept in the file long term (because this component just doesn't play with local state preservation).

As a side note, the string format is actually a temporary quick fix. What I really want is a comment `// @!hmr` or `<!-- @!hmr -->` (or even `/* @!hmr */` in CSS). But that needs to be implemented in each bundler plugin (webpack, rollup), because `svelte-hmr` only sees the compiled code, where comments have been stripped. So this is more a low cost implementation for testing the idea of the feature for now.

Maybe it could be useful to disable preservation for just some specific variables in the file?

```js
// @!hmr myVar, myOtherVar
```

**Comment by rixo** [comment] 2020-02-28 22:58
Hey @jsprog! This should now be fixed with last version of the plugins for Rollup or Webpack, and Svelte 3.19+. Can you confirm if your initial problem is fixed?

**Comment by jsprog** [comment] 2020-03-04 13:34
Hello rixo and sorry for the delay.

After doing some tests with **_svelte-template-hot_** today. I can say that the problems mentioned above are solved.
- HMR is not messing with DOM bindings anymore
- HMR is restoring locale state before calling onMount

About optional restoration for locale state at component level (e.g: @!hmr), I can't recommend anything at the moment.

You may close this issue.

Best Regards

**Comment by rixo** [comment] 2020-03-04 13:42
Great :) Thanks for feedback!

Regarding temp / local bailing out of local state preservation, I've implemented it more like I wanted it now. If the string `@!hmr` appears _anywhere_ in your component's source, then local state won't be preserved for the next HMR update (and as long as the magic string is present).

You'd most likely add it as a comment somewhere in your file `// @!hmr`. Could be at the top, if it's intended to remain there, or just beside your cursor if it's a one shot thing.

In case of conflict with your source (even I don't see how... writing docs for svelte-hmr maybe?), you can change the string with `noPreserveLocalStateKey` option.

Cheers!

**Closed as completed by rixo** 2020-03-04 13:42 UTC
Labels: bug
